In [7]:
'wodid'[:1]

'w'

In [24]:
# Python program for insert and search 
# operation in a Trie 

class TrieNode: 

    # Trie node class 
    def __init__(self, word): 
        self.children = [None]*26

        # isEndOfWord is True if node represent the end of the word 
        self.isEndOfWord = False
        self.word = word

class Trie: 

    # Trie data structure class 
    def __init__(self): 
        self.root = self.getNode('') 

    def getNode(self, word): 

        # Returns new trie node (initialized to NULLs) 
        return TrieNode(word) 

    def _charToIndex(self,ch): 

        # private helper function 
        # Converts key current character into index 
        # use only 'a' through 'z' and lower case 

        return ord(ch)-ord('a') 


    def insert(self,key): 

        # If not present, inserts key into trie 
        # If the key is prefix of trie node, 
        # just marks leaf node 
        pCrawl = self.root 
        length = len(key) 
        for level in range(length): 
            index = self._charToIndex(key[level]) 

            # if current character is not present 
            if not pCrawl.children[index]: 
                pCrawl.children[index] = self.getNode(key[:level+1]) 
            pCrawl = pCrawl.children[index] 

        # mark last node as leaf 
        pCrawl.isEndOfWord = True

    def search(self, key): 

        # Search key in the trie 
        # Returns true if key presents 
        # in trie, else false 
        pCrawl = self.root 
        length = len(key) 
        for level in range(length): 
            index = self._charToIndex(key[level]) 
            if not pCrawl.children[index]: 
                return False
            pCrawl = pCrawl.children[index] 

        return pCrawl != None and pCrawl.isEndOfWord 
    
    def search_partial(self, key): 

        # Search key in the trie 
        # Returns true if key presents 
        # in trie, else false 
        pCrawl = self.root 
        length = len(key) 
        for level in range(length): 
            index = self._charToIndex(key[level]) 
            if not pCrawl.children[index]: 
                return False
            pCrawl = pCrawl.children[index] 
            
        return self.leaves(pCrawl)
    
    def leaves(self, node):
        words = []
        if node.isEndOfWord:
            words.append(node.word)
        for child in node.children:
            if child is not None:
                words = words + self.leaves(child)
        return words
            
        
            
        

In [25]:

# Input keys (use only 'a' through 'z' and lower case) 
keys = ["the","a","there","anaswe","any", 
        "by","their"] 
output = ["Not present in trie", 
        "Present in trie"] 

# Trie object 
t = Trie() 

# Construct trie 
for key in keys: 
    t.insert(key) 

# Search for different keys 
print("{} ---- {}".format("the",output[t.search("the")])) 
print("{} ---- {}".format("these",output[t.search("these")])) 
print("{} ---- {}".format("their",output[t.search("their")])) 
print("{} ---- {}".format("thaw",output[t.search("thaw")])) 



the ---- Present in trie
these ---- Not present in trie
their ---- Present in trie
thaw ---- Not present in trie


In [26]:
t.search_partial('b')

['by']

In [ ]:
    # Please write your code here.
    
    # get unique tags, retain order
    tags = np.array(training_tags)
    _, idx = np.unique(tags, return_index=True)
    
    # preserve order
    u_tags = tags[np.sort(idx)]
    
    if tag in u_tags:
        i = np.where(u_tags == tag)
        i = int(i[0][0])+1
    else:
        i = 0

In [ ]:
training_tags

In [92]:
tag = 'POP'
training_tags = ['METAL','METAL','POP','ROCK']

def solution(tag, training_tags):
    u_tags = set(training_tags)
    if tag in u_tags:
        return sorted(list(u_tags)).index(tag)+1
    else:
        return 0
    

In [95]:
solution('P', training_tags)

0

In [96]:
sorted(['a','b','a'])

['a', 'a', 'b']

In [45]:
training_tags = []

In [49]:
sorted(training_tags)

['METAL', 'METAL', 'POP', 'ROCK']

In [40]:
import numpy as np

In [60]:
print(training_tags)
tags = np.array(training_tags)
s, idx = np.unique(tags, return_index=True)
print(idx)
u_tags = tags[np.sort(idx)]
i = np.where(u_tags == tag)

['METAL', 'METAL', 'POP', 'ROCK']
[0 2 3]


In [61]:
idx

array([0, 2, 3])

In [43]:
Tag indexer

You're given a list of string tags (the "training data") and a query tag. The idea is to write a Python3 function to map the tag to an integer index based on the training data.

The output integer should reflect the position of the input tag in the list of unique tags as sorted by Python (starting at 1). Unknown tags should be mapped to 0.

You can use native Python or any of the packages available (see Info).

You can look at some test cases for inspiration.

(array([], dtype=int64),)

In [ ]:
Write a function in Python3 that takes two lists of integers and returns a string depending on the cosine similarity between the two lists (interpreted as vectors). Return the string "True" if the cosine similarity is greater 0, or the string "False" otherwise. If the lists are not compatible, return "NA".

You can use native Python or any of the packages available (see Info).

You can look at some test cases for inspiration.

In [42]:
int(i[0][0])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
u_tags

In [31]:
u_tags

array(['METAL', 'POP', 'ROCK'], dtype='<U5')

In [51]:
arr1 = np.random.randn(5)

In [58]:
np.reshape([1,2,3,4,5,7], (2,3))

array([[1, 2, 3],
       [4, 5, 7]])

In [54]:
np.linalg.norm(arr1)

2.9189147909418582

In [56]:
arr1.dot(arr1)**0.5

2.9189147909418582

In [73]:
P = [5,7,3,87,67,104]
U = 3
n=0

In [74]:
# Please write your code here.
P = np.array(P)

# find num items to reshape
I = len(P)//U
P_matrix = P.reshape(U, I)

# sum across columns
play_count = np.sum(P_matrix,0)

# sort descending and get first n
top_n = (-play_count).argsort()[:n]

In [75]:
P_matrix

array([[  5,   7],
       [  3,  87],
       [ 67, 104]])

In [76]:
play_count

array([ 75, 198])

In [85]:
a = [4, 3]
b = [1, 1, 5, 5]

len_a = len(a)
len_b = len(b)

n = min(len_a, len_b)
a.reverse()

def sumprod(x,y):
    return sum(x_i*y_i for x_i, y_i in zip(x,y))

diff = len_b-len_a

[sumprod(a,b[i:i+len_a]) for i in range(diff+1)]

[7, 23, 35]

In [84]:
diff

2